### ISSUE TITLE
Not able to build covnetjs using ant

### ISSUE THREAD

**Issue by manishbansal8843** [karpathy/convnetjs#87]
I tried running ant from build.xml directory. It is able to run concat target, but throwing error at compress target. Below are the logs.

``` 
Buildfile: C:\Users\manish_bansal01\Desktop\106Work\Covenetjs\convnetjs-master\convnetjs-master\compile\build.xml

concatenate:

compress:
    [apply] java.io.FileNotFoundException: Usersmanish_bansal01Desktop106WorkCov
enetjsconvnetjs-masterconvnetjs-mastercompile..buildconvnet-min.js:\Users\manish
_bansal01\Desktop\106Work\Covenetjs\convnetjs-master\convnetjs-master\build\conv
net.js (The filename, directory name, or volume label syntax is incorrect)
    [apply]     at java.io.FileOutputStream.open(Native Method)
    [apply]     at java.io.FileOutputStream.<init>(FileOutputStream.java:212)
    [apply]     at java.io.FileOutputStream.<init>(FileOutputStream.java:104)
    [apply]     at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompr
essor.java:183)
    [apply]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [apply]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcces
sorImpl.java:57)
    [apply]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMet
hodAccessorImpl.java:43)
    [apply]     at java.lang.reflect.Method.invoke(Method.java:601)
    [apply]     at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.ja
va:21)
    [apply] Result: 1

BUILD SUCCESSFUL
Total time: 3 seconds
```

**Comment by null77** [comment]
Having the same issue, seems to a Windows path-related issue.

**Comment by 371148606** [comment]
您好，我是薛文毅，已收到您的邮件，一会查收，谢谢！！
